version: "2"
services:
  postgres:
    container_name: class_postgres_1
    image: postgres:11.1
    restart: unless-stopped
    networks:
      - my-net
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "myuser-pw!"
      POSTGRES_DB: "gogs"
    volumes:
     - "../../../postgres/data/data:/var/lib/postgresql/data"
networks:
  my-net:
    driver: bridge
